### ISSUE TITLE
Docker "Failed to launch chrome!"

### ISSUE THREAD

**Issue by mlekorlz** [paschmann/changd#20]
While running docker image, it's unable to get website screenshot.

changd-ui   | 192.168.65.1 - - [26/Jul/2024:10:29:33 +0000] "GET /api/v1/jobs/2 HTTP/1.1" 200 1067 "http://localhost:8081/jobs/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
changd-api  | https://google.com
changd-api  | Unable to get website screenshot: Error: Failed to launch chrome!
changd-api  | [57:57:0726/102936.931958:ERROR:browser_main_loop.cc(1485)] Unable to open X display.
changd-api  | TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
changd-api  | Unable to capture screenshot
changd-api  | Error: Image unable to be captured or differences detected.
changd-api  | Error: ENOENT: no such file or directory, unlink './screenshots/2/rmw9r_diff.png'
changd-api  |     at Object.unlinkSync (fs.js:1210:3)
changd-api  |     at Object.deleteFile (/app/db/file_handler.js:95:10)
changd-api  |     at executeVisualJob (/app/db/job_daemon.js:507:19)
changd-api  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
changd-api  |     at async /app/db/job_daemon.js:167:9 {
changd-api  |   errno: -2,
changd-api  |   syscall: 'unlink',
changd-api  |   code: 'ENOENT',
changd-api  |   path: './screenshots/2/rmw9r_diff.png'
changd-api  | }

**Comment by scubbx** [comment]
It seems to me that after this commit (https://github.com/paschmann/changd/commit/51e386e530ca541d2970ad2657acc1b7deb3201d#diff-0b013f15ba214974a2b092d590d3608e033cac4e865b68209ae3d984e727d7caL521) the Chrome-Browser now needs a X11 display address.

Maybe a virtual framebuffer with xvfb that is launched just before the chrom(ium) binary would work?

**Comment by mehmetkocali** [comment]
Same problem here, any ideas on how to solve this issue?
