### ISSUE TITLE
unable to create screenshot (no such file or directory, mkdir 'screenshots/1/')

### ISSUE THREAD

**Issue by wivaku** [paschmann/changd#8]
After fresh install and adding visual test I get an error message when run / test.
Probably because `mkdir 'screenshots/1/` fails.

Maybe a permission issue?
Can I pass on UID/GUID environment variables to the api docker container?

Related: should / can I mount a folder in my docker-compose that is to be used for screenshots?

```
changd-api  | Unable to get website screenshot: Error: ENOENT: no such file or directory, mkdir 'screenshots/1/'
changd-api  | Unable to capture screenshot
changd-api  | Error: Image unable to be captured or differences detected.
changd-api  | Error: ENOENT: no such file or directory, unlink './screenshots/1/a8y2s_diff.png'
changd-api  |     at Object.unlinkSync (fs.js:1210:3)
changd-api  |     at Object.deleteFile (/app/db/file_handler.js:78:8)
changd-api  |     at executeVisualJob (/app/db/job_daemon.js:504:19)
changd-api  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
changd-api  |     at async /app/db/job_daemon.js:165:9 {
changd-api  |   errno: -2,
changd-api  |   syscall: 'unlink',
changd-api  |   code: 'ENOENT',
changd-api  |   path: './screenshots/1/a8y2s_diff.png'
changd-api  | }
changd-api  | Error: ENOENT: no such file or directory, unlink './screenshots/1/a8y2s.png'
changd-api  |     at Object.unlinkSync (fs.js:1210:3)
changd-api  |     at Object.deleteFile (/app/db/file_handler.js:78:8)
changd-api  |     at executeVisualJob (/app/db/job_daemon.js:505:19)
changd-api  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
changd-api  |     at async /app/db/job_daemon.js:165:9 {
changd-api  |   errno: -2,
changd-api  |   syscall: 'unlink',
changd-api  |   code: 'ENOENT',
changd-api  |   path: './screenshots/1/a8y2s.png'
changd-api  | }
```

**Comment by paschmann** [comment]
Thanks for the helpful details @wivaku - I believe this is now resolved with 1.3.0.
